### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by hvitis** [Cloud-CNC/vue-gcode-viewer#9]
Hello

I would like to ask if you guys need any help with this?

**Comment by Wakeful-Cloud** [comment]
@hvitis Yes, I'd love help with this repo. With respect to if it's still maintained: yes in theory, but not often enough. I jump around quite a bit within Cloud CNC's repositories, and this one was definitely getting neglected.

### Roadmap
In the very short term, I'd like to add automatic publishing to NPM. In the more distant future, especially since the 1.0.0 release of [cura-wasm](https://github.com/cloud-cnc/cura-wasm) is out, this repository is probably going to get renamed to something like `vue-cnc-viewer` (I'm open to other suggestions) and gain the ability to open other related 3D formats such as `.ply`, `.obj`, and `.stl`. *To me, it seems inefficient to make separate repositories that would do similar things and likely end up with identical dependencies especially when ThreeJS is massive and webpack doesn't work super well on it (If I remember correctly). However, please don't feel any obligation to work on any of these; feel free to work on whatever you'd like.*

[Edit]
I created a spectrum community/channel https://spectrum.chat/cloud-cnc/vue-gcode-viewer

**Comment by Wakeful-Cloud** [comment]
Closed due to inactivity
